{
 "title": "Aztec GitHub Actions Workflow Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Workflow Runs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(workflow_runs_count{workflow_file=\"ci3.yml\", status!=\"completed\"}[$__interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workflow_runs_count{workflow_file=\"ci3.yml\", status!=\"completed\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Runs Status (-5m)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workflow_runs_count{workflow_file=\"ci3.yml\", status!=\"completed\"} offset 5m",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Runs Status (-1h)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workflow_runs_count{workflow_file=\"ci3.yml\", status!=\"completed\"} offset 1h",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Workflow Duration - Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, workflow_runs_duration_seconds{workflow_file=\"ci3.yml\"}[$__range])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.9, workflow_runs_duration_seconds{workflow_file=\"ci3.yml\"}[$__range])",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}